### ISSUE TITLE
Cannot start Webside

### ISSUE THREAD

**Issue by johbra** [guillermoamaral/Pharo-Webside#1]
Loading Webside with
```
Metacello new
	baseline: 'Webside';
	repository: 'github://guillermoamaral/Pharo-Webside:main';
	load
```
no problem. 

Starting web server with
```
WebsideServer new
	baseUri: '/pharo/v1';
	port: 9002;
        start
```

But trying

localhost:9002/pharo/v1

I get

Method Not Allowed GET /pharo/v1

**Comment by guillermoamaral** [comment]
Hi!

That is because at localhost:9002/pharo/v1 you have the backend (API endpoints supporting the access to Pharo), but from your browser you should run the frontend.
You can access to an available online version of the frontend at https://websideserver.azurewebsites.net. There you will be prompted for the backend URL, the one you chose when you started WebsideServer in Pharo (http://localhost:9002/pharo/v1 in your example). It is also possible to specify both backend and developer in the URL and access directly to https://websideserver.azurewebsites.net/ide?baseUri=http://localhost:9002/pharo/v1&dialect=Pharo&developer=johbra.

Finally, if you want to have the frontend running locally in your machine, you should clone https://github.com/guillermoamaral/Webside and follow the installation/usage steps (https://github.com/guillermoamaral/Webside#installation).

Regards,

**Comment by guillermoamaral** [comment]
Hi,

First, could access thru this https://websideserver.azurewebsites.net/ide?baseUri=http://localhost:9002/pharo/v1&dialect=Pharo&developer=johbra<https://websideserver.azurewebsites.net/ide?baseUri=http://localhost:9002/pharo/v1&dialect=Pharo&developer=johbra.>? You can try Webside and work in Pharo with this option without the "pain" of dealing with installation of npm dependencies, etc.

Second, if what you want is to put hands on React code of the frontend, yes, you should go with this option.
I followed the installation steps in my machine and it worked:

  1.  git clone https://github.com/guillermoamaral/Webside.git
  2.  cd client (it is important for the moment to be under that directory when both installing npm dependencies and running)
  3.  npm install
  4.  npm start

I have Node.js v16.16.0 installed in my machine.

Regards,

________________________________


Guillermo Amaral
Development Manager
Office +1 281 254 7600
www.quorumsoftware.com

_
_

Confidentiality Notice:
 The information transmitted herein may contain confidential, proprietary and/or privileged material which belongs to Quorum Software and is only for the intended addressee(s). Any unauthorized review, distribution or other use of this information is prohibited. Finally, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email. If you received this email in error, please contact us at +1 (713) 430 8600 or by return email and delete this email and any copies immediately.  v&7.11.1989&$
From: johbra ***@***.***>
Sent: Wednesday, October 12, 2022 11:21
To: guillermoamaral/Pharo-Webside ***@***.***>
Cc: Guillermo Amaral ***@***.***>; State change ***@***.***>
Subject: [EXT] Re: [guillermoamaral/Pharo-Webside] Cannot start Webside (Issue #1)


 CAUTION: This email originated from outside of Quorum.

Hi!

thank you for your help, but ...

That is because at localhost:9002/pharo/v1 you have the backend (API endpoints supporting the access to Pharo), but from your browser you should run the frontend.

You can access to an available online version of the frontend at https://websideserver.azurewebsites.net<https://websideserver.azurewebsites.net/>. There you will be prompted for the backend URL, the one you chose when you started WebsideServer in Pharo (http://localhost:9002/pharo/v1 in your example). It is also possible to specify both backend and developer in the URL and access directly to https://websideserver.azurewebsites.net/ide?baseUri=http://localhost:9002/pharo/v1&dialect=Pharo&developer=johbra.

… after I did this:

Finally, if you want to have the frontend running locally in your machine, you should clone https://github.com/guillermoamaral/Webside and follow the installation/usage steps (https://github.com/guillermoamaral/Webside#installation).

entering npm start I get:

Failed to compile.

Module not found: Error: Can't resolve 'recompose/withStateHandlers' in '/Users/jb/tmp/Webside/client/src/components/dialogs'
ERROR in ./src/components/dialogs/ListDialog.js 6:0-60
Module not found: Error: Can't resolve 'recompose/withStateHandlers' in '/Users/jb/tmp/Webside/client/src/components/dialogs'

ERROR in ./src/components/dialogs/PromptDialog.js 6:0-60
Module not found: Error: Can't resolve 'recompose/withStateHandlers' in '/Users/jb/tmp/Webside/client/src/components/dialogs'

webpack compiled with 2 errors

Regards

Johannes
