### ISSUE TITLE
What versions of Pharo have been tested?

### ISSUE THREAD

**Issue by peterode** [guillermoamaral/Pharo-Webside#2]
I love what you're doing with Webside.
Which versions of Pharo are tested and good-to-go with Webside?
Please add to your documentation. Thanks

**Comment by guillermoamaral** [comment]
Hey Peter, thanks!

It's been a while since the last real development (I'm just one and other projects stole my entire capacity). Hopefully, I will be able to continue using it (for real, with other people) and developing it in the near future.

In the case of Pharo, it works on Pharo 10 (I had moved it from Pharo 9, which implied a few touches, before showing it in ESUG 22). I just updated the documentation.

Regards,
